WITH 
AAPL AS (
    SELECT DATE, DAILY_CLOSE AS AAPL_CLOSE
    FROM {{ ref('src_aapl') }}
),
MSFT AS (
    SELECT DATE, DAILY_CLOSE AS MSFT_CLOSE
    FROM {{ ref('src_msft') }}
),
TSLA AS (
    SELECT DATE, DAILY_CLOSE AS TSLA_CLOSE
    FROM {{ ref('src_tsla') }}
),
SPY AS (
    SELECT DATE, DAILY_CLOSE AS SPY_CLOSE
    FROM {{ ref('src_spy') }}
)

SELECT
    AAPL.DATE,
    AAPL.AAPL_CLOSE,
    MSFT.MSFT_CLOSE,
    TSLA.TSLA_CLOSE,
    SPY.SPY_CLOSE
FROM AAPL
JOIN MSFT ON AAPL.DATE = MSFT.DATE
JOIN TSLA ON AAPL.DATE = TSLA.DATE
JOIN SPY ON AAPL.DATE = SPY.DATE
