WITH daily_returns AS (
    SELECT *
    FROM {{ ref('daily_returns') }}
),
mean_returns AS (
    SELECT
        AVG(AAPL_RETURN) AS AAPL_AVG_RETURN,
        AVG(MSFT_RETURN) AS MSFT_AVG_RETURN,
        AVG(TSLA_RETURN) AS TSLA_AVG_RETURN,
        AVG(SPY_RETURN) AS SPY_AVG_RETURN
    FROM daily_returns
),
daily_deviations AS (
    SELECT
        daily_returns.DATE,
        (AAPL_RETURN - AAPL_AVG_RETURN) * (SPY_RETURN - SPY_AVG_RETURN) AS AAPL_SPY_DEV_PROD,
        (MSFT_RETURN - MSFT_AVG_RETURN) * (SPY_RETURN - SPY_AVG_RETURN) AS MSFT_SPY_DEV_PROD,
        (TSLA_RETURN - TSLA_AVG_RETURN) * (SPY_RETURN - SPY_AVG_RETURN) AS TSLA_SPY_DEV_PROD,
        (SPY_RETURN - SPY_AVG_RETURN) * (SPY_RETURN - SPY_AVG_RETURN) AS SPY_DEV_SQ
    FROM daily_returns, mean_returns
),
cumulative_sums AS (
    SELECT
        DATE,
        SUM(AAPL_SPY_DEV_PROD) OVER (ORDER BY DATE) AS AAPL_SPY_CUM_DEV_PROD,
        SUM(MSFT_SPY_DEV_PROD) OVER (ORDER BY DATE) AS MSFT_SPY_CUM_DEV_PROD,
        SUM(TSLA_SPY_DEV_PROD) OVER (ORDER BY DATE) AS TSLA_SPY_CUM_DEV_PROD,
        SUM(SPY_DEV_SQ) OVER (ORDER BY DATE) AS SPY_CUM_DEV_SQ
    FROM daily_deviations
)

SELECT
    DATE,
    AAPL_SPY_CUM_DEV_PROD / SPY_CUM_DEV_SQ AS AAPL_BETA,
    MSFT_SPY_CUM_DEV_PROD / SPY_CUM_DEV_SQ AS MSFT_BETA,
    TSLA_SPY_CUM_DEV_PROD / SPY_CUM_DEV_SQ AS TSLA_BETA
FROM cumulative_sums
